-- ============================================================================
-- JobPilot seed data - GENERATED, do not edit by hand.
--   source: data/cvbuilder/  |  generator: scripts/import-cvbuilder.ts
--   regenerate: npm run seed:build      generated: 2026-09-02
--
-- Run supabase/schema.sql first, then this file (npm run db:seed, or paste it
-- into the Supabase SQL editor). It upserts, so it is safe to re-run.
-- The workspace owner (parag.m.rahangdale@gmail.com) must have signed in at least once, so
-- that an auth.users row exists for the profile to hang off.
-- ============================================================================
do $seed$
declare
  uid uuid;
begin
  select id into uid from auth.users where lower(email) = lower('parag.m.rahangdale@gmail.com') limit 1;
  if uid is null then
    raise exception 'JobPilot seed: no auth.users row for %. Sign in to the app once, then re-run.', 'parag.m.rahangdale@gmail.com';
  end if;

  insert into profiles (user_id, display_name, target_geos, role_families, networks, visa_context, premium_llm_budget_usd_month, contact_lines, cv_extras)
  values (uid, 'Parag Rahangdale', array['Singapore']::text[], array['consulting', 'project-management', 'product-management', 'product-strategy', 'engineering-manager']::text[], '[{"name":"INSEAD","program":"MBA Class of December 2026","location":"Singapore/France"},{"name":"Indian Institute of Technology, Jodhpur (IIT)","program":"Bachelor of Technology in System Science","location":"Jodhpur, India"}]'::jsonb, 'Indian; currently holding a Singapore Student Visa (valid until Jan 2027)', 0, array['https://www.linkedin.com/in/paragr', 'parag.rahangdale@insead.edu / parag.m.rahangdale@gmail.com', '+65 89869790 / +91 8197475525']::text[], '[{"id":"add-auth","label":"Nationality/Authorisation","text":"Indian; currently holding a Singapore Student Visa (valid until Jan 2027)","locked":true},{"id":"add-lang","label":"Languages","text":"English (Native), Hindi (Native), Spanish (Beginner)","locked":true},{"id":"add-skills","label":"Skills","text":"Leadership | People Management | Project Management | Budget and Resource Management | Product Management","locked":false,"tailorable":true},{"id":"add-tech","label":"Technologies","text":"AI | Blockchain | Kubernetes | Containerisation | Quantum Computing | Automation and Scripting | MCP","locked":false,"tailorable":true},{"id":"add-interests","label":"Interests","text":"Mentorship/Coaching | Exploring Emerging Tech | High-Altitude Trekking | Strategic Gaming | Japanese Media & Art","locked":false,"tailorable":true}]'::jsonb)
  on conflict (user_id) do update set display_name = excluded.display_name, target_geos = excluded.target_geos, role_families = excluded.role_families, networks = excluded.networks, visa_context = excluded.visa_context, premium_llm_budget_usd_month = excluded.premium_llm_budget_usd_month, contact_lines = excluded.contact_lines, cv_extras = excluded.cv_extras;

  insert into sectors (id, user_id, path, role_family, skills, companies, titles, jd_count, summary)
  values ('57a607d5-4dcb-857b-8123-e229ac0d03d3'::uuid, uid, array['Management Consulting', 'Singapore']::text[], null::text, '{"strategy-consulting":1}'::jsonb, array['BCG (Boston Consulting Group)']::text[], array['Consultant, Singapore (Post-MBA)']::text[], 1, 'Management Consulting > Singapore: 1 JD(s) imported from CVbuilder (BCG (Boston Consulting Group)). Most-demanded: strategy-consulting.')
  on conflict (user_id, path) do update set role_family = excluded.role_family, skills = excluded.skills, companies = excluded.companies, titles = excluded.titles, jd_count = excluded.jd_count, summary = excluded.summary;

  insert into sectors (id, user_id, path, role_family, skills, companies, titles, jd_count, summary)
  values ('f0f52f92-0193-8958-8e75-41165bb34be0'::uuid, uid, array['Product Management', 'Singapore']::text[], null::text, '{"launch":2,"revenue":2,"sales-partnership":1,"growth":2,"gtm":1,"customer-facing":1,"ops-execution":2,"people-management":1,"team-leadership":1,"cross-functional":2,"influence":1,"data-analysis":2,"metrics-kpi":1,"stakeholder-management":2,"cloud-infra":2,"ai-ml":1,"strategy-consulting":1,"product-management":1,"prioritization":1,"process-improvement":1,"compliance":1,"budget-management":1,"quality":1,"ambiguity":1}'::jsonb, array['Microsoft', 'Tiktok']::text[], array['Regional Partner Development Manager, Singapore', 'Product Manager Project Intern (TikTok Live-Ecosystem Governance)']::text[], 2, 'Product Management > Singapore: 2 JD(s) imported from CVbuilder (Microsoft, Tiktok). Most-demanded: cloud-infra, cross-functional, data-analysis, growth, launch.')
  on conflict (user_id, path) do update set role_family = excluded.role_family, skills = excluded.skills, companies = excluded.companies, titles = excluded.titles, jd_count = excluded.jd_count, summary = excluded.summary;

  insert into projects (id, user_id, name, org, dates, role, narrative, outcomes, skills, sector_tags)
  values ('79a53177-b96e-88f5-87af-41d3946a48ad'::uuid, uid, 'Valeo Health - Management Intern', 'Valeo Health', 'Jul - Aug 2026', 'Management Intern', 'Major home healthtech provider in the UAE, bringing medical services to patients at home', '{}'::text[], array['automation', 'cross-functional', 'data-analysis', 'discovery', 'influence', 'launch', 'metrics-kpi', 'ops-execution', 'pricing', 'prioritization', 'process-improvement', 'product-management', 'research', 'scaling-ops', 'strategy-consulting', 'zero-to-one']::text[], '{}'::uuid[])
  on conflict (id) do update set name = excluded.name, org = excluded.org, dates = excluded.dates, role = excluded.role, narrative = excluded.narrative, outcomes = excluded.outcomes, skills = excluded.skills, sector_tags = excluded.sector_tags;

  insert into projects (id, user_id, name, org, dates, role, narrative, outcomes, skills, sector_tags)
  values ('d33a4d2b-59b4-8c4d-883e-c81f173ac715'::uuid, uid, 'EverHaus Group - Product Strategy Manager', 'EverHaus Group', 'Jan - May 2026', 'Product Strategy Manager', 'Singapore-based proptech investment platform democratising access to high-yield real estate renovation projects', '{}'::text[], array['ai-ml', 'ambiguity', 'compliance', 'cross-functional', 'discovery', 'founding', 'process-improvement', 'product-management', 'product-ops', 'product-strategy', 'research', 'roadmap', 'scaling-ops', 'strategy-consulting', 'zero-to-one']::text[], '{}'::uuid[])
  on conflict (id) do update set name = excluded.name, org = excluded.org, dates = excluded.dates, role = excluded.role, narrative = excluded.narrative, outcomes = excluded.outcomes, skills = excluded.skills, sector_tags = excluded.sector_tags;

  insert into projects (id, user_id, name, org, dates, role, narrative, outcomes, skills, sector_tags)
  values ('9e0d2909-94da-8eeb-8736-29f501d0a303'::uuid, uid, 'Nutanix - Team Lead, Engineering', 'Nutanix', '2024 - 2026', 'Team Lead, Engineering', 'Nutanix simplifies IT with a hybrid multi-cloud platform for managing storage, computing and networking', '{}'::text[], array['agile-jira', 'ai-ml', 'automation', 'budget-management', 'cross-functional', 'customer-facing', 'data-migration', 'discovery', 'engineering', 'ops-execution', 'people-management', 'prioritization', 'process-improvement', 'product-ops', 'product-strategy', 'project-management', 'revenue', 'sales-partnership', 'stakeholder-management', 'team-leadership']::text[], '{}'::uuid[])
  on conflict (id) do update set name = excluded.name, org = excluded.org, dates = excluded.dates, role = excluded.role, narrative = excluded.narrative, outcomes = excluded.outcomes, skills = excluded.skills, sector_tags = excluded.sector_tags;

  insert into projects (id, user_id, name, org, dates, role, narrative, outcomes, skills, sector_tags)
  values ('002033e9-b352-875b-8cba-241d4570e663'::uuid, uid, 'Nutanix - Member of Technical Staff', 'Nutanix', '2022 - 2024', 'Member of Technical Staff', 'Nutanix simplifies IT with a hybrid multi-cloud platform for managing storage, computing and networking', '{}'::text[], array['cross-functional', 'customer-facing', 'data-migration', 'engineering', 'launch', 'process-improvement', 'quality', 'revenue', 'team-leadership', 'zero-to-one']::text[], '{}'::uuid[])
  on conflict (id) do update set name = excluded.name, org = excluded.org, dates = excluded.dates, role = excluded.role, narrative = excluded.narrative, outcomes = excluded.outcomes, skills = excluded.skills, sector_tags = excluded.sector_tags;

  insert into projects (id, user_id, name, org, dates, role, narrative, outcomes, skills, sector_tags)
  values ('bc435cd2-eaf9-87d0-892f-4e4ed1dcab38'::uuid, uid, 'Touchnote - Backend Developer', 'Touchnote', '2020 - 2022', 'Backend Developer', 'United Kingdom-based platform to send personalised postcards/greeting cards/canvases and gifts', '{}'::text[], array['backend', 'conversion', 'cross-functional', 'customer-facing', 'engineering', 'experimentation', 'growth', 'gtm', 'launch', 'metrics-kpi', 'product-management', 'revenue']::text[], '{}'::uuid[])
  on conflict (id) do update set name = excluded.name, org = excluded.org, dates = excluded.dates, role = excluded.role, narrative = excluded.narrative, outcomes = excluded.outcomes, skills = excluded.skills, sector_tags = excluded.sector_tags;

  insert into projects (id, user_id, name, org, dates, role, narrative, outcomes, skills, sector_tags)
  values ('f7bfa839-bb65-8307-85d9-67ed3746a2ef'::uuid, uid, 'Eleven01 - Blockchain Developer and Founding Member', 'Eleven01', '2019 - 2020', 'Blockchain Developer and Founding Member', 'Blockchain startup that provides scalable and secure decentralised solutions for businesses across various industries', '{}'::text[], array['ambiguity', 'blockchain', 'engineering', 'founding', 'hiring-culture', 'launch', 'people-management', 'product-strategy', 'roadmap', 'scaling-ops', 'team-leadership', 'zero-to-one']::text[], '{}'::uuid[])
  on conflict (id) do update set name = excluded.name, org = excluded.org, dates = excluded.dates, role = excluded.role, narrative = excluded.narrative, outcomes = excluded.outcomes, skills = excluded.skills, sector_tags = excluded.sector_tags;

  insert into projects (id, user_id, name, org, dates, role, narrative, outcomes, skills, sector_tags)
  values ('2592ce1e-31b6-8920-843d-4dfa9e18a248'::uuid, uid, 'Amantya Technologies - Software Engineer', 'Amantya Technologies', '2018', 'Software Engineer', 'A service company in the telecom space, specialising in 5G and IoT solutions to drive innovation and enhance connectivity.', '{}'::text[], array['conversion', 'customer-facing', 'engineering', 'growth', 'mobile']::text[], '{}'::uuid[])
  on conflict (id) do update set name = excluded.name, org = excluded.org, dates = excluded.dates, role = excluded.role, narrative = excluded.narrative, outcomes = excluded.outcomes, skills = excluded.skills, sector_tags = excluded.sector_tags;

  insert into projects (id, user_id, name, org, dates, role, narrative, outcomes, skills, sector_tags)
  values ('697c6394-c1de-8ce2-89d5-d3c835dab15a'::uuid, uid, 'Cognizant - Associate', 'Cognizant', '2016 - 2018', 'Associate', 'Cognizant is a global technology services company specialising in IT consulting, digital transformation and business process outsourcing', '{}'::text[], array['automation', 'cloud-infra', 'cross-functional', 'engineering', 'ops-execution', 'process-improvement']::text[], '{}'::uuid[])
  on conflict (id) do update set name = excluded.name, org = excluded.org, dates = excluded.dates, role = excluded.role, narrative = excluded.narrative, outcomes = excluded.outcomes, skills = excluded.skills, sector_tags = excluded.sector_tags;

  insert into projects (id, user_id, name, org, dates, role, narrative, outcomes, skills, sector_tags)
  values ('2c39bdb4-926d-83da-828a-86e035944c92'::uuid, uid, 'INSEAD - MBA Class of December 2026', 'INSEAD', '2026', 'MBA Class of December 2026', '', '{}'::text[], array['blockchain', 'influence', 'team-leadership']::text[], '{}'::uuid[])
  on conflict (id) do update set name = excluded.name, org = excluded.org, dates = excluded.dates, role = excluded.role, narrative = excluded.narrative, outcomes = excluded.outcomes, skills = excluded.skills, sector_tags = excluded.sector_tags;

  insert into projects (id, user_id, name, org, dates, role, narrative, outcomes, skills, sector_tags)
  values ('1ea05ffe-0294-8564-8bd3-830271311cec'::uuid, uid, 'Indian Institute of Technology, Jodhpur (IIT) - Bachelor of Technology in System Science', 'Indian Institute of Technology, Jodhpur (IIT)', '2012 - 2016', 'Bachelor of Technology in System Science', '', '{}'::text[], array['influence', 'mentorship', 'people-management', 'project-management', 'revenue', 'sales-partnership', 'team-leadership']::text[], '{}'::uuid[])
  on conflict (id) do update set name = excluded.name, org = excluded.org, dates = excluded.dates, role = excluded.role, narrative = excluded.narrative, outcomes = excluded.outcomes, skills = excluded.skills, sector_tags = excluded.sector_tags;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('91b29285-22a4-847f-8f9a-bd812fb8aab7'::uuid, uid, '79a53177-b96e-88f5-87af-41d3946a48ad'::uuid, 'consulting', 'Traced an 18% rise in fleet operating cost against 0% revenue growth to its underlying drivers, building the financial analysis that framed the cost problem', array['data-analysis', 'metrics-kpi', 'research', 'strategy-consulting', 'ops-execution', 'pricing']::text[], '[{"label":"short","text":"Traced an 18% rise in fleet operating cost against 0% revenue growth to its underlying drivers"},{"label":"analysis-forward","text":"Ran the financial analysis isolating why fleet operating cost rose 18% while revenue stayed flat, naming each underlying driver"},{"label":"cursor-forward","text":"Traced an 18% rise in fleet operating cost against 0% revenue growth to its underlying drivers, building the financial analysis in Cursor"}]'::jsonb, 5)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('8e8cb5dd-4c65-8a5b-8453-f371e8f37073'::uuid, uid, '79a53177-b96e-88f5-87af-41d3946a48ad'::uuid, 'consulting', 'Developed two strategies to cut fleet cost by up to 30%: consolidating the two verticals and building a three-hub network that shortens the distance driven per order', array['strategy-consulting', 'process-improvement', 'scaling-ops', 'ops-execution', 'prioritization', 'influence']::text[], '[{"label":"short","text":"Developed two strategies to cut fleet cost by up to 30%, including a three-hub network that shortens distance driven per order"},{"label":"consulting-forward","text":"Sized two levers to cut fleet cost by up to 30% — merging the two verticals and moving to a three-hub network — against the measured cost drivers"},{"label":"cursor-forward","text":"Developed two strategies to cut fleet cost by up to 30%: consolidating the two verticals and building a three-hub network that shortens the distance driven per order, sizing the saving from each in Cursor"}]'::jsonb, 5)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('eae0e24b-cc40-86e1-8005-781faf553a89'::uuid, uid, '79a53177-b96e-88f5-87af-41d3946a48ad'::uuid, 'consulting', 'Learned how the operation ran from the people running it, then specified and prototyped the route-optimisation app they needed — 100% adoption in one week', array['product-management', 'discovery', 'cross-functional', 'launch', 'zero-to-one', 'influence', 'automation', 'ops-execution']::text[], '[{"label":"ai-forward","text":"Specified and prototyped the route-optimisation app the operations team needed, building it end-to-end with AI, reaching 100% adoption in one week"},{"label":"short","text":"Prototyped a route-optimisation app with the operations team and drove it to 100% adoption in one week"},{"label":"adoption-forward","text":"Drove a route-optimisation app to 100% adoption by the operations team within one week of putting the prototype in their hands"},{"label":"digitisation-forward","text":"Digitised fleet operations with a route-optimisation app specified alongside the operations team, reaching 100% adoption within one week"}]'::jsonb, 5)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('a08745d8-a5cd-89ae-862a-ba74a3d18a36'::uuid, uid, 'd33a4d2b-59b4-8c4d-883e-c81f173ac715'::uuid, 'general', 'Developed the product roadmap for a bootstrapped renovation-investment platform, defining 20+ core features using AI-driven research', array['product-management', 'product-strategy', 'roadmap', 'ai-ml', 'research', 'zero-to-one', 'discovery']::text[], '[{"label":"ai-forward","text":"Used AI-driven research to define 20+ core features and build the product roadmap for a bootstrapped renovation-investment platform"},{"label":"zero-to-one","text":"Built the product roadmap for a bootstrapped renovation-investment platform from a blank page, defining 20+ core features through AI-driven market and user research"}]'::jsonb, 4)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('db26b093-479b-84f5-83bd-b6275137a9bd'::uuid, uid, 'd33a4d2b-59b4-8c4d-883e-c81f173ac715'::uuid, 'general', 'Owned compliance research and product strategy for a lean founding team, shaping a platform targeting up to 16% annual returns', array['compliance', 'product-strategy', 'research', 'ambiguity', 'founding', 'strategy-consulting']::text[], '[{"label":"ops-forward","text":"Owned regulatory and compliance research end-to-end for a lean founding team, translating findings into product requirements for a platform targeting up to 16% annual returns"},{"label":"ambiguity-forward","text":"Operated with no playbook on a lean founding team, owning compliance research and product strategy for a platform targeting up to 16% annual returns"}]'::jsonb, 4)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('39b4c98b-cf9c-852d-8e64-183745005c65'::uuid, uid, 'd33a4d2b-59b4-8c4d-883e-c81f173ac715'::uuid, 'consulting', 'Defined the AI-first operating model for a founding team, up and running in 2 months instead of 6 and reaching a demo product and investor conversations far sooner', array['product-ops', 'scaling-ops', 'process-improvement', 'zero-to-one', 'founding', 'cross-functional', 'ai-ml']::text[], '[{"label":"short","text":"Stood up an AI-first operating model in 2 months instead of 6, reaching a demo product and investor conversations far sooner"},{"label":"ops-forward","text":"Built the operating model that lets non-technical founders run engineering — progress tracked in Notion, requests raised in Linear, delivery by AI coding agents — cutting setup from 6 months to 2"},{"label":"investor-forward","text":"Cut the team''s path to a demo product and investor conversations from 6 months to 2 by designing an AI-first operating model around Notion, Linear and AI coding agents"}]'::jsonb, 4)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('2241ae66-500c-8b08-8220-4f4aa053e850'::uuid, uid, '9e0d2909-94da-8eeb-8736-29f501d0a303'::uuid, 'consulting', 'Optimised development workflow with AI tooling and JIRA, delivering 50% fewer meetings and 20% faster product cycles', array['product-ops', 'process-improvement', 'automation', 'ai-ml', 'agile-jira', 'ops-execution']::text[], '[{"label":"product-ops","text":"Redesigned the team''s development workflow around AI tooling and JIRA, cutting meetings 50% and shortening product cycles 20%"},{"label":"process-forward","text":"Eliminated 50% of recurring meetings and shortened product cycles 20% by rebuilding the development workflow with AI tooling and JIRA"}]'::jsonb, 4)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('fe429335-8105-8f3b-8249-982191883323'::uuid, uid, '9e0d2909-94da-8eeb-8736-29f501d0a303'::uuid, 'consulting', 'Drove product strategy with Sales to prioritise customer-driven features, enabling $40–50M in Annual Contract Value', array['product-strategy', 'prioritization', 'sales-partnership', 'revenue', 'cross-functional', 'customer-facing', 'stakeholder-management', 'discovery']::text[], '[{"label":"customer-forward","text":"Partnered with Sales to translate customer needs into a prioritised feature set, enabling $40–50M in Annual Contract Value"},{"label":"xfn-forward","text":"Aligned Sales, Product and Engineering on a single prioritised roadmap driven by customer input, enabling $40–50M in Annual Contract Value"}]'::jsonb, 5)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('a5871493-1d1d-80c1-808f-51072faa5109'::uuid, uid, '9e0d2909-94da-8eeb-8736-29f501d0a303'::uuid, 'product-strategy', 'Managed a team of 11+ developers and a $500K budget to deliver best-in-class migration software recognised by Gartner', array['people-management', 'team-leadership', 'budget-management', 'project-management', 'data-migration', 'engineering']::text[], '[{"label":"people-forward","text":"Led and developed a team of 11+ engineers against a $500K budget, shipping migration software recognised by Gartner as best-in-class"},{"label":"delivery-forward","text":"Delivered Gartner-recognised migration software on a $500K budget with a team of 11+ developers"},{"label":"budget-forward","text":"Ran a $500K budget and an 11+ person team to deliver migration software Gartner rated best-in-class"}]'::jsonb, 5)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('be4f0e34-ae4c-8b12-8d05-8d28ed4d71fa'::uuid, uid, '002033e9-b352-875b-8cba-241d4570e663'::uuid, 'general', 'Spearheaded the creation of a files migration feature, led cross-organisational collaboration to onboard customers with 10+ petabytes of data, resulting in $1M+ in recurring revenue', array['zero-to-one', 'cross-functional', 'customer-facing', 'revenue', 'data-migration', 'engineering', 'launch']::text[], '[{"label":"grammar-fixed","text":"Spearheaded a new files migration capability and led cross-organisational collaboration to onboard customers with 10+ petabytes of data, generating $1M+ in recurring revenue"},{"label":"customer-forward","text":"Onboarded enterprise customers holding 10+ petabytes of data onto a new files migration capability, unlocking $1M+ in recurring revenue"}]'::jsonb, 5)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('f8b8fc94-73db-8726-8dec-ff38d699d8ae'::uuid, uid, '002033e9-b352-875b-8cba-241d4570e663'::uuid, 'engineering-manager', 'Introduced initiatives to establish coding standards, resulting in a 30% improvement in code quality and fewer customer defects', array['quality', 'process-improvement', 'engineering', 'team-leadership']::text[], '[{"label":"process-forward","text":"Established team-wide coding standards and review practices, improving code quality 30% and reducing customer-reported defects"},{"label":"quality-forward","text":"Drove a 30% improvement in code quality and a drop in customer-reported defects by introducing team-wide coding standards"}]'::jsonb, 3)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('adfdf518-8e6c-8832-89e4-a1b44cd2f6ba'::uuid, uid, 'bc435cd2-eaf9-87d0-892f-4e4ed1dcab38'::uuid, 'general', 'Revamped the checkout process, saving customers 30 seconds per checkout; optimisation led to an improved Customer Conversion Rate, reduced Cart Abandonment, and increased Average Order Value for a global customer base', array['conversion', 'growth', 'metrics-kpi', 'customer-facing', 'backend', 'engineering', 'experimentation']::text[], '[{"label":"short","text":"Revamped the checkout flow to save 30 seconds per purchase, lifting Conversion Rate and Average Order Value while reducing Cart Abandonment across a global customer base"},{"label":"metrics-forward","text":"Improved Conversion Rate and Average Order Value and cut Cart Abandonment for a global customer base by rebuilding checkout to save 30 seconds per purchase"},{"label":"ops-forward","text":"Removed 30 seconds of friction per checkout by rebuilding the flow, improving Conversion Rate and Average Order Value and cutting Cart Abandonment for a global customer base"}]'::jsonb, 4)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('153e4c2b-ef1a-80e5-8f89-e2ff87bc339d'::uuid, uid, 'bc435cd2-eaf9-87d0-892f-4e4ed1dcab38'::uuid, 'general', 'Drove business expansion by collaborating with the Product team to identify and launch a new e-commerce platform feature, establishing a new revenue stream of $25K+/month, rolled out across United Kingdom', array['growth', 'revenue', 'launch', 'cross-functional', 'gtm', 'product-management']::text[], '[{"label":"short","text":"Identified and launched a new e-commerce feature with the Product team, opening a $25K+/month revenue stream across the United Kingdom"},{"label":"revenue-forward","text":"Opened a $25K+/month revenue stream by identifying and launching a new e-commerce platform feature with the Product team, rolled out across the United Kingdom"}]'::jsonb, 4)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('1b2d57b0-87b2-814e-85a6-59448ee91516'::uuid, uid, 'f7bfa839-bb65-8307-85d9-67ed3746a2ef'::uuid, 'product-management', 'Architected the foundational blockchain MVP and strategic product roadmap as a founding member, while establishing the core cultural values and operational standards required to scale the technical organisation', array['founding', 'zero-to-one', 'blockchain', 'product-strategy', 'roadmap', 'hiring-culture', 'scaling-ops', 'engineering', 'ambiguity']::text[], '[{"label":"short","text":"Architected the foundational blockchain MVP and product roadmap as a founding member, setting the cultural values and operational standards used to scale the technical organisation"},{"label":"zero-to-one","text":"Took a blockchain platform from zero to MVP as a founding member, owning the technical architecture, product roadmap, and the operating standards the organisation scaled on"}]'::jsonb, 5)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('ee9b2374-270c-837e-883e-a7205e9171b6'::uuid, uid, 'f7bfa839-bb65-8307-85d9-67ed3746a2ef'::uuid, 'engineering-manager', 'Led a 10+ member team to develop multiple differentiating features for the Eleven01 blockchain, culminating in an Initial Coin Offering', array['team-leadership', 'people-management', 'blockchain', 'launch', 'engineering']::text[], '[{"label":"grammar-fixed","text":"Led a 10+ member team to build the differentiating features of the Eleven01 blockchain, culminating in an Initial Coin Offering"},{"label":"people-forward","text":"Led a 10+ member team through the build of the Eleven01 blockchain''s differentiating features, culminating in an Initial Coin Offering"},{"label":"launch-forward","text":"Shipped the differentiating features of the Eleven01 blockchain with a 10+ member team, culminating in an Initial Coin Offering"}]'::jsonb, 4)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('34b22f2d-e9c4-87ff-8a94-b55121674477'::uuid, uid, '2592ce1e-31b6-8920-843d-4dfa9e18a248'::uuid, 'general', 'Boosted footfall and sales for brick-and-mortar retailers by 10% by developing an iOS app; sending hyper-local and personalised offers to users within a shopping mall', array['mobile', 'growth', 'customer-facing', 'engineering', 'conversion']::text[], '[{"label":"short","text":"Lifted footfall and sales 10% for brick-and-mortar retailers by building an iOS app that pushed hyper-local, personalised offers to shoppers inside a mall"},{"label":"growth-forward","text":"Drove a 10% lift in footfall and sales for brick-and-mortar retailers with an iOS app delivering hyper-local, personalised offers to shoppers in-mall"}]'::jsonb, 3)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('6cbc0e7f-b217-80c5-896f-98d3ec98e02d'::uuid, uid, '697c6394-c1de-8ce2-89d5-d3c835dab15a'::uuid, 'consulting', 'Built automation to bring down platform deployment time of complex IoT solution from 5–6 days to 1 hour by leading a cross-team initiative to build a deployment platform', array['automation', 'process-improvement', 'cloud-infra', 'cross-functional', 'engineering', 'ops-execution']::text[], '[{"label":"short","text":"Cut deployment time for a complex IoT solution from 5–6 days to 1 hour by leading a cross-team initiative to build a deployment automation platform"},{"label":"ops-forward","text":"Led a cross-team initiative that automated platform deployment for a complex IoT solution, collapsing a 5-6 day manual process into 1 hour"}]'::jsonb, 4)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('a1353dee-1ecc-8fc8-8913-be3ab47b8df0'::uuid, uid, '2c39bdb4-926d-83da-828a-86e035944c92'::uuid, 'general', 'President, Fintech & Blockchain Club | GMAT Focus: 695', array['team-leadership', 'blockchain', 'influence']::text[], '[{"label":"leadership-forward","text":"President, Fintech & Blockchain Club (largest student club by membership) | GMAT Focus: 695"},{"label":"academics-forward","text":"GMAT Focus: 695 | President, Fintech & Blockchain Club"}]'::jsonb, 5)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('5ccbb970-954c-85da-8b85-bfd475c6f6d2'::uuid, uid, '1ea05ffe-0294-8564-8bd3-830271311cec'::uuid, 'general', 'Mentored junior students, directly achieving a 10% rise in average GPA through individualised academic support and mentorship', array['mentorship', 'people-management', 'influence']::text[], '[{"label":"people-forward","text":"Coached junior students one-to-one, lifting their average GPA 10% through individualised academic support"},{"label":"short","text":"Raised mentees'' average GPA 10% through one-to-one academic coaching of junior students"}]'::jsonb, 3)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into bullets (id, user_id, project_id, role_family, text, skills, variants, strength)
  values ('2be373ed-28ad-85df-858d-f831ebc84307'::uuid, uid, '1ea05ffe-0294-8564-8bd3-830271311cec'::uuid, 'general', 'Served as Workshop Head for the annual college festival Ignus, generating $10K in revenue through strategic partnerships and sales', array['revenue', 'sales-partnership', 'project-management', 'team-leadership']::text[], '[{"label":"commercial-forward","text":"Generated $10K in revenue as Workshop Head of the annual college festival Ignus by securing corporate partnerships and driving delegate sales"},{"label":"ops-forward","text":"As Workshop Head for the annual college festival Ignus, delivered $10K in revenue by securing partnerships and driving sales"}]'::jsonb, 3)
  on conflict (id) do update set project_id = excluded.project_id, role_family = excluded.role_family, text = excluded.text, skills = excluded.skills, variants = excluded.variants, strength = excluded.strength;

  insert into master_cvs (id, user_id, role_family, summary_line, bullet_ids, version)
  values ('23264bb6-36a5-87e0-89d9-7242bcec8ee8'::uuid, uid, 'consulting', 'Parag Rahangdale - Management Consulting | INSEAD MBA Class of December 2026', array['a1353dee-1ecc-8fc8-8913-be3ab47b8df0'::uuid, '2be373ed-28ad-85df-858d-f831ebc84307'::uuid, '91b29285-22a4-847f-8f9a-bd812fb8aab7'::uuid, '8e8cb5dd-4c65-8a5b-8453-f371e8f37073'::uuid, 'eae0e24b-cc40-86e1-8005-781faf553a89'::uuid, 'db26b093-479b-84f5-83bd-b6275137a9bd'::uuid, 'a08745d8-a5cd-89ae-862a-ba74a3d18a36'::uuid, '39b4c98b-cf9c-852d-8e64-183745005c65'::uuid, 'a5871493-1d1d-80c1-808f-51072faa5109'::uuid, 'fe429335-8105-8f3b-8249-982191883323'::uuid, '2241ae66-500c-8b08-8220-4f4aa053e850'::uuid, 'be4f0e34-ae4c-8b12-8d05-8d28ed4d71fa'::uuid, '153e4c2b-ef1a-80e5-8f89-e2ff87bc339d'::uuid, '1b2d57b0-87b2-814e-85a6-59448ee91516'::uuid, '6cbc0e7f-b217-80c5-896f-98d3ec98e02d'::uuid]::uuid[], 1)
  on conflict (user_id, role_family, version) do update set summary_line = excluded.summary_line, bullet_ids = excluded.bullet_ids;

  insert into master_cvs (id, user_id, role_family, summary_line, bullet_ids, version)
  values ('014d07fd-886a-849b-8276-a3019edb6a63'::uuid, uid, 'project-management', 'Parag Rahangdale - Project / Programme Management | INSEAD MBA Class of December 2026', array['a1353dee-1ecc-8fc8-8913-be3ab47b8df0'::uuid, '2be373ed-28ad-85df-858d-f831ebc84307'::uuid, 'eae0e24b-cc40-86e1-8005-781faf553a89'::uuid, '8e8cb5dd-4c65-8a5b-8453-f371e8f37073'::uuid, '39b4c98b-cf9c-852d-8e64-183745005c65'::uuid, 'a5871493-1d1d-80c1-808f-51072faa5109'::uuid, 'fe429335-8105-8f3b-8249-982191883323'::uuid, '2241ae66-500c-8b08-8220-4f4aa053e850'::uuid, 'be4f0e34-ae4c-8b12-8d05-8d28ed4d71fa'::uuid, 'adfdf518-8e6c-8832-89e4-a1b44cd2f6ba'::uuid, '1b2d57b0-87b2-814e-85a6-59448ee91516'::uuid, '34b22f2d-e9c4-87ff-8a94-b55121674477'::uuid, '6cbc0e7f-b217-80c5-896f-98d3ec98e02d'::uuid]::uuid[], 1)
  on conflict (user_id, role_family, version) do update set summary_line = excluded.summary_line, bullet_ids = excluded.bullet_ids;

  insert into master_cvs (id, user_id, role_family, summary_line, bullet_ids, version)
  values ('c0230b33-6f99-8815-8a43-eb0f5d8419cd'::uuid, uid, 'product-management', 'Parag Rahangdale - Product Management | INSEAD MBA Class of December 2026', array['a1353dee-1ecc-8fc8-8913-be3ab47b8df0'::uuid, '2be373ed-28ad-85df-858d-f831ebc84307'::uuid, 'eae0e24b-cc40-86e1-8005-781faf553a89'::uuid, '91b29285-22a4-847f-8f9a-bd812fb8aab7'::uuid, '8e8cb5dd-4c65-8a5b-8453-f371e8f37073'::uuid, 'a08745d8-a5cd-89ae-862a-ba74a3d18a36'::uuid, '39b4c98b-cf9c-852d-8e64-183745005c65'::uuid, 'fe429335-8105-8f3b-8249-982191883323'::uuid, 'be4f0e34-ae4c-8b12-8d05-8d28ed4d71fa'::uuid, '153e4c2b-ef1a-80e5-8f89-e2ff87bc339d'::uuid, '1b2d57b0-87b2-814e-85a6-59448ee91516'::uuid, '34b22f2d-e9c4-87ff-8a94-b55121674477'::uuid, '6cbc0e7f-b217-80c5-896f-98d3ec98e02d'::uuid]::uuid[], 1)
  on conflict (user_id, role_family, version) do update set summary_line = excluded.summary_line, bullet_ids = excluded.bullet_ids;

  insert into master_cvs (id, user_id, role_family, summary_line, bullet_ids, version)
  values ('716c37cd-24d0-80e7-8cf9-90390b1aa28f'::uuid, uid, 'product-strategy', 'Parag Rahangdale - Product Strategy | INSEAD MBA Class of December 2026', array['a1353dee-1ecc-8fc8-8913-be3ab47b8df0'::uuid, '5ccbb970-954c-85da-8b85-bfd475c6f6d2'::uuid, '91b29285-22a4-847f-8f9a-bd812fb8aab7'::uuid, '8e8cb5dd-4c65-8a5b-8453-f371e8f37073'::uuid, 'db26b093-479b-84f5-83bd-b6275137a9bd'::uuid, 'a08745d8-a5cd-89ae-862a-ba74a3d18a36'::uuid, 'fe429335-8105-8f3b-8249-982191883323'::uuid, 'a5871493-1d1d-80c1-808f-51072faa5109'::uuid, 'be4f0e34-ae4c-8b12-8d05-8d28ed4d71fa'::uuid, '153e4c2b-ef1a-80e5-8f89-e2ff87bc339d'::uuid, '1b2d57b0-87b2-814e-85a6-59448ee91516'::uuid, '34b22f2d-e9c4-87ff-8a94-b55121674477'::uuid, '6cbc0e7f-b217-80c5-896f-98d3ec98e02d'::uuid]::uuid[], 1)
  on conflict (user_id, role_family, version) do update set summary_line = excluded.summary_line, bullet_ids = excluded.bullet_ids;

  insert into master_cvs (id, user_id, role_family, summary_line, bullet_ids, version)
  values ('1b9ae7af-4b68-8841-8425-c7538463fbc9'::uuid, uid, 'engineering-manager', 'Parag Rahangdale - Engineering Management | INSEAD MBA Class of December 2026', array['a1353dee-1ecc-8fc8-8913-be3ab47b8df0'::uuid, '5ccbb970-954c-85da-8b85-bfd475c6f6d2'::uuid, '8e8cb5dd-4c65-8a5b-8453-f371e8f37073'::uuid, '39b4c98b-cf9c-852d-8e64-183745005c65'::uuid, 'a5871493-1d1d-80c1-808f-51072faa5109'::uuid, '2241ae66-500c-8b08-8220-4f4aa053e850'::uuid, 'f8b8fc94-73db-8726-8dec-ff38d699d8ae'::uuid, 'be4f0e34-ae4c-8b12-8d05-8d28ed4d71fa'::uuid, 'adfdf518-8e6c-8832-89e4-a1b44cd2f6ba'::uuid, '1b2d57b0-87b2-814e-85a6-59448ee91516'::uuid, 'ee9b2374-270c-837e-883e-a7205e9171b6'::uuid, '34b22f2d-e9c4-87ff-8a94-b55121674477'::uuid, '6cbc0e7f-b217-80c5-896f-98d3ec98e02d'::uuid]::uuid[], 1)
  on conflict (user_id, role_family, version) do update set summary_line = excluded.summary_line, bullet_ids = excluded.bullet_ids;

  insert into master_cvs (id, user_id, role_family, summary_line, bullet_ids, version)
  values ('b18a9204-4ff3-89ee-811f-1600bcfb52b6'::uuid, uid, 'general', 'Parag Rahangdale | INSEAD MBA Class of December 2026', array['a1353dee-1ecc-8fc8-8913-be3ab47b8df0'::uuid, '5ccbb970-954c-85da-8b85-bfd475c6f6d2'::uuid, '2be373ed-28ad-85df-858d-f831ebc84307'::uuid, 'a08745d8-a5cd-89ae-862a-ba74a3d18a36'::uuid, 'db26b093-479b-84f5-83bd-b6275137a9bd'::uuid, '2241ae66-500c-8b08-8220-4f4aa053e850'::uuid, 'fe429335-8105-8f3b-8249-982191883323'::uuid, 'a5871493-1d1d-80c1-808f-51072faa5109'::uuid, 'be4f0e34-ae4c-8b12-8d05-8d28ed4d71fa'::uuid, 'f8b8fc94-73db-8726-8dec-ff38d699d8ae'::uuid, 'adfdf518-8e6c-8832-89e4-a1b44cd2f6ba'::uuid, '153e4c2b-ef1a-80e5-8f89-e2ff87bc339d'::uuid, '1b2d57b0-87b2-814e-85a6-59448ee91516'::uuid, 'ee9b2374-270c-837e-883e-a7205e9171b6'::uuid, '34b22f2d-e9c4-87ff-8a94-b55121674477'::uuid, '6cbc0e7f-b217-80c5-896f-98d3ec98e02d'::uuid]::uuid[], 1)
  on conflict (user_id, role_family, version) do update set summary_line = excluded.summary_line, bullet_ids = excluded.bullet_ids;

  insert into master_cvs (id, user_id, role_family, summary_line, bullet_ids, version)
  values ('a3d421cf-2d5e-89d5-87fa-7bbbec5b323d'::uuid, uid, 'general', 'Parag Rahangdale | INSEAD MBA Class of December 2026', array['a1353dee-1ecc-8fc8-8913-be3ab47b8df0'::uuid, '2be373ed-28ad-85df-858d-f831ebc84307'::uuid, 'eae0e24b-cc40-86e1-8005-781faf553a89'::uuid, '91b29285-22a4-847f-8f9a-bd812fb8aab7'::uuid, '8e8cb5dd-4c65-8a5b-8453-f371e8f37073'::uuid, 'a08745d8-a5cd-89ae-862a-ba74a3d18a36'::uuid, 'db26b093-479b-84f5-83bd-b6275137a9bd'::uuid, 'fe429335-8105-8f3b-8249-982191883323'::uuid, 'a5871493-1d1d-80c1-808f-51072faa5109'::uuid, '2241ae66-500c-8b08-8220-4f4aa053e850'::uuid, 'be4f0e34-ae4c-8b12-8d05-8d28ed4d71fa'::uuid, 'adfdf518-8e6c-8832-89e4-a1b44cd2f6ba'::uuid, '153e4c2b-ef1a-80e5-8f89-e2ff87bc339d'::uuid, '1b2d57b0-87b2-814e-85a6-59448ee91516'::uuid, 'ee9b2374-270c-837e-883e-a7205e9171b6'::uuid, '6cbc0e7f-b217-80c5-896f-98d3ec98e02d'::uuid]::uuid[], 2)
  on conflict (user_id, role_family, version) do update set summary_line = excluded.summary_line, bullet_ids = excluded.bullet_ids;

  insert into application_cvs (id, user_id, master_cv_id, diff, bullet_ids, summary_line, file_path)
  values ('4cbf015f-5c28-8a1d-8ccf-f4336e9c5075'::uuid, uid, (select id from master_cvs where user_id = uid and role_family = 'consulting' and version = 1), '{"addBulletIds":[],"removeBulletIds":[],"keywordsToMirror":["strategy"],"summaryLine":"Parag Rahangdale - Management Consulting | INSEAD MBA Class of December 2026, targeting Consultant, Singapore (Post-MBA) at BCG (Boston Consulting Group).","variants":{"8e8cb5dd-4c65-8a5b-8453-f371e8f37073":"short","eae0e24b-cc40-86e1-8005-781faf553a89":"ai-forward","a08745d8-a5cd-89ae-862a-ba74a3d18a36":"ai-forward","39b4c98b-cf9c-852d-8e64-183745005c65":"investor-forward","fe429335-8105-8f3b-8249-982191883323":"xfn-forward","a5871493-1d1d-80c1-808f-51072faa5109":"people-forward","be4f0e34-ae4c-8b12-8d05-8d28ed4d71fa":"customer-forward","153e4c2b-ef1a-80e5-8f89-e2ff87bc339d":"short","6cbc0e7f-b217-80c5-896f-98d3ec98e02d":"short"}}'::jsonb, array['91b29285-22a4-847f-8f9a-bd812fb8aab7'::uuid, '8e8cb5dd-4c65-8a5b-8453-f371e8f37073'::uuid, 'eae0e24b-cc40-86e1-8005-781faf553a89'::uuid, 'a08745d8-a5cd-89ae-862a-ba74a3d18a36'::uuid, 'db26b093-479b-84f5-83bd-b6275137a9bd'::uuid, '39b4c98b-cf9c-852d-8e64-183745005c65'::uuid, 'fe429335-8105-8f3b-8249-982191883323'::uuid, '2241ae66-500c-8b08-8220-4f4aa053e850'::uuid, 'a5871493-1d1d-80c1-808f-51072faa5109'::uuid, 'be4f0e34-ae4c-8b12-8d05-8d28ed4d71fa'::uuid, '153e4c2b-ef1a-80e5-8f89-e2ff87bc339d'::uuid, '1b2d57b0-87b2-814e-85a6-59448ee91516'::uuid, '6cbc0e7f-b217-80c5-896f-98d3ec98e02d'::uuid, 'a1353dee-1ecc-8fc8-8913-be3ab47b8df0'::uuid, '2be373ed-28ad-85df-858d-f831ebc84307'::uuid]::uuid[], 'Parag Rahangdale - Management Consulting | INSEAD MBA Class of December 2026, targeting Consultant, Singapore (Post-MBA) at BCG (Boston Consulting Group).', null::text)
  on conflict (id) do update set master_cv_id = excluded.master_cv_id, diff = excluded.diff, bullet_ids = excluded.bullet_ids, summary_line = excluded.summary_line, file_path = excluded.file_path;

  insert into application_cvs (id, user_id, master_cv_id, diff, bullet_ids, summary_line, file_path)
  values ('109e0add-fad3-874b-844a-98497a2dff43'::uuid, uid, (select id from master_cvs where user_id = uid and role_family = 'product-management' and version = 1), '{"addBulletIds":["2241ae66-500c-8b08-8220-4f4aa053e850","a5871493-1d1d-80c1-808f-51072faa5109","adfdf518-8e6c-8832-89e4-a1b44cd2f6ba","ee9b2374-270c-837e-883e-a7205e9171b6"],"removeBulletIds":["8e8cb5dd-4c65-8a5b-8453-f371e8f37073","1b2d57b0-87b2-814e-85a6-59448ee91516","34b22f2d-e9c4-87ff-8a94-b55121674477"],"keywordsToMirror":["revenue","sales","growth","gtm","cross-functional","influence","ai"],"summaryLine":"Parag Rahangdale - Product Management | INSEAD MBA Class of December 2026, targeting Regional Partner Development Manager, Singapore at Microsoft.","variants":{"fe429335-8105-8f3b-8249-982191883323":"customer-forward","be4f0e34-ae4c-8b12-8d05-8d28ed4d71fa":"customer-forward","a5871493-1d1d-80c1-808f-51072faa5109":"people-forward","91b29285-22a4-847f-8f9a-bd812fb8aab7":"short","eae0e24b-cc40-86e1-8005-781faf553a89":"ai-forward","a08745d8-a5cd-89ae-862a-ba74a3d18a36":"ai-forward","39b4c98b-cf9c-852d-8e64-183745005c65":"short","153e4c2b-ef1a-80e5-8f89-e2ff87bc339d":"revenue-forward","adfdf518-8e6c-8832-89e4-a1b44cd2f6ba":"short","ee9b2374-270c-837e-883e-a7205e9171b6":"grammar-fixed","6cbc0e7f-b217-80c5-896f-98d3ec98e02d":"short","2be373ed-28ad-85df-858d-f831ebc84307":"commercial-forward"}}'::jsonb, array['fe429335-8105-8f3b-8249-982191883323'::uuid, 'be4f0e34-ae4c-8b12-8d05-8d28ed4d71fa'::uuid, '2241ae66-500c-8b08-8220-4f4aa053e850'::uuid, 'a5871493-1d1d-80c1-808f-51072faa5109'::uuid, '91b29285-22a4-847f-8f9a-bd812fb8aab7'::uuid, 'eae0e24b-cc40-86e1-8005-781faf553a89'::uuid, 'a08745d8-a5cd-89ae-862a-ba74a3d18a36'::uuid, '39b4c98b-cf9c-852d-8e64-183745005c65'::uuid, '153e4c2b-ef1a-80e5-8f89-e2ff87bc339d'::uuid, 'adfdf518-8e6c-8832-89e4-a1b44cd2f6ba'::uuid, 'ee9b2374-270c-837e-883e-a7205e9171b6'::uuid, '6cbc0e7f-b217-80c5-896f-98d3ec98e02d'::uuid, 'a1353dee-1ecc-8fc8-8913-be3ab47b8df0'::uuid, '2be373ed-28ad-85df-858d-f831ebc84307'::uuid]::uuid[], 'Parag Rahangdale - Product Management | INSEAD MBA Class of December 2026, targeting Regional Partner Development Manager, Singapore at Microsoft.', null::text)
  on conflict (id) do update set master_cv_id = excluded.master_cv_id, diff = excluded.diff, bullet_ids = excluded.bullet_ids, summary_line = excluded.summary_line, file_path = excluded.file_path;

  insert into application_cvs (id, user_id, master_cv_id, diff, bullet_ids, summary_line, file_path)
  values ('1095022f-7a14-8b0d-85e3-7373e51f9bb5'::uuid, uid, (select id from master_cvs where user_id = uid and role_family = 'product-management' and version = 1), '{"addBulletIds":["db26b093-479b-84f5-83bd-b6275137a9bd","2241ae66-500c-8b08-8220-4f4aa053e850","a5871493-1d1d-80c1-808f-51072faa5109","f8b8fc94-73db-8726-8dec-ff38d699d8ae","ee9b2374-270c-837e-883e-a7205e9171b6"],"removeBulletIds":["a08745d8-a5cd-89ae-862a-ba74a3d18a36","1b2d57b0-87b2-814e-85a6-59448ee91516"],"keywordsToMirror":["prioritization","launch","revenue","expansion","collaboration","quality"],"summaryLine":"Parag Rahangdale - Product Management | INSEAD MBA Class of December 2026, targeting Product Manager Project Intern (TikTok Live-Ecosystem Governance) at Tiktok.","variants":{"eae0e24b-cc40-86e1-8005-781faf553a89":"short","39b4c98b-cf9c-852d-8e64-183745005c65":"investor-forward"}}'::jsonb, array['91b29285-22a4-847f-8f9a-bd812fb8aab7'::uuid, 'eae0e24b-cc40-86e1-8005-781faf553a89'::uuid, '8e8cb5dd-4c65-8a5b-8453-f371e8f37073'::uuid, 'db26b093-479b-84f5-83bd-b6275137a9bd'::uuid, '39b4c98b-cf9c-852d-8e64-183745005c65'::uuid, 'fe429335-8105-8f3b-8249-982191883323'::uuid, '2241ae66-500c-8b08-8220-4f4aa053e850'::uuid, 'a5871493-1d1d-80c1-808f-51072faa5109'::uuid, 'be4f0e34-ae4c-8b12-8d05-8d28ed4d71fa'::uuid, 'f8b8fc94-73db-8726-8dec-ff38d699d8ae'::uuid, '153e4c2b-ef1a-80e5-8f89-e2ff87bc339d'::uuid, 'ee9b2374-270c-837e-883e-a7205e9171b6'::uuid, '34b22f2d-e9c4-87ff-8a94-b55121674477'::uuid, '6cbc0e7f-b217-80c5-896f-98d3ec98e02d'::uuid, 'a1353dee-1ecc-8fc8-8913-be3ab47b8df0'::uuid, '2be373ed-28ad-85df-858d-f831ebc84307'::uuid]::uuid[], 'Parag Rahangdale - Product Management | INSEAD MBA Class of December 2026, targeting Product Manager Project Intern (TikTok Live-Ecosystem Governance) at Tiktok.', null::text)
  on conflict (id) do update set master_cv_id = excluded.master_cv_id, diff = excluded.diff, bullet_ids = excluded.bullet_ids, summary_line = excluded.summary_line, file_path = excluded.file_path;

  insert into applications (id, user_id, company, role, sector_id, stage, closed_reason, jd_extract, jd_raw, cv_id, referral_contact_id, next_action, saved_at, applied_at, updated_at)
  values ('3f775461-7914-834b-88f2-c38d256c8b63'::uuid, uid, 'BCG (Boston Consulting Group)', 'Consultant, Singapore (Post-MBA)', (select id from sectors where user_id = uid and path = array['Management Consulting', 'Singapore']::text[]), 'saved'::app_stage, null::closed_reason, '{"company":"BCG (Boston Consulting Group)","role":"Consultant, Singapore (Post-MBA)","roleFamily":"consulting","sectorPath":["Management Consulting","Singapore"],"skills":["strategy-consulting"],"keywords":["strategy","consulting","mba"],"seniority":null,"visaNote":"Eligibility: This role is open to INSEAD 26D students, IE MBAs graduating between Dec 2026 - Mar 2027, and second year MBA students from ESADE, IESE, HEC, and LBS, who are seeking full-time roles.","location":"Singapore"}'::jsonb, 'Eligibility: This role is open to INSEAD 26D students, IE MBAs graduating between Dec 2026 - Mar 2027, and second year MBA students from ESADE, IESE, HEC, and LBS, who are seeking full-time roles.

Boston Consulting Group partners with leaders in business and society to tackle their most important challenges and capture their greatest opportunities. BCG was the pioneer in business strategy when it was founded in 1963. Today, we help clients with total transformation-inspiring complex change, enabling organizations to grow, building competitive advantage, and driving bottom-line impact.

To succeed, organizations must blend digital and human capabilities. Our diverse, global teams bring deep industry and functional expertise and a range of perspectives to spark change. BCG delivers solutions through leading-edge management consulting along with technology and design, corporate and digital ventures-and business purpose. We work in a uniquely collaborative model across the firm and throughout all levels of the client organization, generating results that allow our clients to thrive.', '4cbf015f-5c28-8a1d-8ccf-f4336e9c5075'::uuid, null::uuid, 'Imported from CVbuilder - confirm whether this was submitted, then advance the stage', '2026-08-26'::date, null::date, '2026-08-26T15:20:53.315Z'::timestamptz)
  on conflict (id) do update set company = excluded.company, role = excluded.role, sector_id = excluded.sector_id, stage = excluded.stage, closed_reason = excluded.closed_reason, jd_extract = excluded.jd_extract, jd_raw = excluded.jd_raw, cv_id = excluded.cv_id, referral_contact_id = excluded.referral_contact_id, next_action = excluded.next_action, saved_at = excluded.saved_at, applied_at = excluded.applied_at, updated_at = excluded.updated_at;

  insert into applications (id, user_id, company, role, sector_id, stage, closed_reason, jd_extract, jd_raw, cv_id, referral_contact_id, next_action, saved_at, applied_at, updated_at)
  values ('79d05a17-4f29-8981-814b-b51b8dc5b859'::uuid, uid, 'Microsoft', 'Regional Partner Development Manager, Singapore', (select id from sectors where user_id = uid and path = array['Product Management', 'Singapore']::text[]), 'saved'::app_stage, null::closed_reason, '{"company":"Microsoft","role":"Regional Partner Development Manager, Singapore","roleFamily":"product-management","sectorPath":["Product Management","Singapore"],"skills":["launch","revenue","sales-partnership","growth","gtm","customer-facing","ops-execution","people-management","team-leadership","cross-functional","influence","data-analysis","metrics-kpi","stakeholder-management","cloud-infra","ai-ml","strategy-consulting"],"keywords":["go-to-market","revenue","sales","account","business development","channel","growth","gtm","customer success","operations","performance management","leadership","cross-functional","influence","executive","insights","data-driven","kpi","stakeholder","stakeholder management","cloud","azure","ai","copilot","mba"],"seniority":"manager","visaNote":null,"location":"Singapore"}'::jsonb, 'Regional Partner Development Manager, Microsoft, Singapore. Job 200044526. Individual-contributor Sales role. 50-75% travel.
The Partner Development Manager (PDM) owns a portfolio of strategic partners and distributors in a region and is responsible for growing Microsoft''s cloud business through them - driving cloud revenue, consumption, customer adds, and renewals across Solution Areas (AI, Security, Modern Work, Azure, Business Applications, Digital and App Innovation).
Core pillars:
1. Partner business leadership - executive relationships, partner business plans, business reviews.
2. Partner transformation - moving partners to cloud, AI and managed services and recurring revenue models, driving Microsoft designations and specializations and marketplace motions.
3. AI and Copilot growth - accelerating AI adoption, partner readiness, and packaged offerings.
4. Ecosystem orchestration - aligning PDMs, Partner Technology Strategists, Customer Success Unit, and Solution Area teams.
5. Performance management - pipeline management, forecasting, data-driven insights, corrective action planning, KPI performance management.
6. Strategic initiatives - regional programs and fiscal year planning.
Required: Bachelor''s degree in Marketing, Business Operations, Computer Science or related field, plus 10 years of experience in partner management, sales, business development, or channel development in the technology industry, or equivalent.
Preferred: track record of growing business through ecosystem partners; executive influence and executive stakeholder management; cloud and enterprise technology depth; cross-functional leadership; cloud, AI, security and digital transformation experience; multi-country regional portfolio management; deep Microsoft partner ecosystem knowledge; MBA.
Skills: Account Management, Customer Success, Business Development, Change Management, Business, Management, go-to-market, GTM, managed services, recurring revenue, business transformation, capability development, market analysis, customer acquisition, renewals, consumption growth.
', '109e0add-fad3-874b-844a-98497a2dff43'::uuid, null::uuid, 'Imported from CVbuilder - confirm whether this was submitted, then advance the stage', '2026-09-02'::date, null::date, '2026-09-02T00:00:00.000Z'::timestamptz)
  on conflict (id) do update set company = excluded.company, role = excluded.role, sector_id = excluded.sector_id, stage = excluded.stage, closed_reason = excluded.closed_reason, jd_extract = excluded.jd_extract, jd_raw = excluded.jd_raw, cv_id = excluded.cv_id, referral_contact_id = excluded.referral_contact_id, next_action = excluded.next_action, saved_at = excluded.saved_at, applied_at = excluded.applied_at, updated_at = excluded.updated_at;

  insert into applications (id, user_id, company, role, sector_id, stage, closed_reason, jd_extract, jd_raw, cv_id, referral_contact_id, next_action, saved_at, applied_at, updated_at)
  values ('968d3fd1-434f-8c3b-825a-d4bd173449a3'::uuid, uid, 'Tiktok', 'Product Manager Project Intern (TikTok Live-Ecosystem Governance)', (select id from sectors where user_id = uid and path = array['Product Management', 'Singapore']::text[]), 'saved'::app_stage, null::closed_reason, '{"company":"Tiktok","role":"Product Manager Project Intern (TikTok Live-Ecosystem Governance)","roleFamily":"product-management","sectorPath":["Product Management","Singapore"],"skills":["product-management","prioritization","launch","revenue","growth","process-improvement","ops-execution","compliance","cross-functional","data-analysis","budget-management","stakeholder-management","cloud-infra","quality","ambiguity"],"keywords":["product manager","prioritization","launch","rollout","revenue","expansion","efficiency","operations","execution","governance","collaboration","insights","data-driven","resource allocation","stakeholder","communication with","infrastructure","quality","fast-paced"],"seniority":"intern","visaNote":null,"location":"Singapore"}'::jsonb, 'Team Introduction:
TikTok LIVE Team is committed to creating real-time interactive scenes. As a new form of content, livestream creates value for all parties in the ecology. Livestream provides users with a unique consumption experience and further generalizes content. It is also a new way of employment to provide more direct fan interaction and deepen relationships to authors; It provides robust and objective revenue to the platform and promotes content exclusivity. It also serves as a "new infrastructure" for the expansion of ecological boundaries.

As a Project Intern, you will contribute to impactful short-term projects and gain hands-on experience in a fast-paced, professional environment. This internship offers the opportunity to develop practical skills, apply your knowledge to real-world challenges, and explore your career interests.
Applications are reviewed on a rolling basis, so we encourage you to apply early.

Responsibilities
1. Product Development & Optimization: Assist in designing and improving LIVE ecosystem governance tools and strategies to enhance content quality and platform safety. Develop user education strategies to promote positive engagement and prevent violations in the livestreaming community.
2. Ecosystem Analysis & Insights: Analyze livestreaming trends, governance challenges, and user behavior to identify risks and improvement opportunities. Leverage data-driven insights to refine governance strategies and optimize moderation processes.
3. Cross-Team Collaboration: Work closely with R&D, operations, Algo, and Data teams to enhance governance efficiency and drive product iterations. Support internal prioritization and resource allocation to ensure smooth execution of governance initiatives.
4. Feature Rollout & Stakeholder Communication: Assist in the launch of new governance features and policies, ensuring clear communication with internal teams and external stakeholders. Monitor and respond to user feedback, continuously refining governance tools to improve livestreaming safety and user experience.
', '1095022f-7a14-8b0d-85e3-7373e51f9bb5'::uuid, null::uuid, 'Imported from CVbuilder - confirm whether this was submitted, then advance the stage', '2026-08-14'::date, null::date, '2026-08-14T06:47:43.401Z'::timestamptz)
  on conflict (id) do update set company = excluded.company, role = excluded.role, sector_id = excluded.sector_id, stage = excluded.stage, closed_reason = excluded.closed_reason, jd_extract = excluded.jd_extract, jd_raw = excluded.jd_raw, cv_id = excluded.cv_id, referral_contact_id = excluded.referral_contact_id, next_action = excluded.next_action, saved_at = excluded.saved_at, applied_at = excluded.applied_at, updated_at = excluded.updated_at;

end
$seed$;
